spring:
  profiles:
    active: prod

aws:
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}
  s3:
    bucket-name: odessey-bucket
    region: ap-northeast-2
    presigned-url-duration: PT1H

logging:
  level:
    org:
      springframework: DEBUG